version = 1

[[analyzers]]
name = "csharp"

[[analyzers]]
name = "kotlin"

  [analyzers.meta]
  runtime_version = "1.8"
  language_version = "1.7"

[[analyzers]]
name = "go"

  [analyzers.meta]
  import_root = "github.com/Bidur2054/eshopContainers"

[[analyzers]]
name = "cxx"

[[analyzers]]
name = "sql"

[[analyzers]]
name = "php"

[[analyzers]]
name = "java"

  [analyzers.meta]
  runtime_version = "11"

[[analyzers]]
name = "ruby"

[[analyzers]]
name = "python"

  [analyzers.meta]
  runtime_version = "3.x.x"

[[analyzers]]
name = "javascript"

[[analyzers]]
name = "ansible"